// <auto-generated />
using System;
using APIProdutos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraProduto.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20220517010033_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIProdutos.Models.Produto", b =>
                {
                    b.Property<int>("CodigoDoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoDoProduto"), 1L, 1);

                    b.Property<int>("CNPJDoFornecedor")
                        .HasColumnType("int");

                    b.Property<int>("CodigoDoFornecedor")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDeFabricação")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDoFornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoDoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SituacaoDoProduto")
                        .HasColumnType("bit");

                    b.HasKey("CodigoDoProduto");

                    b.HasIndex("CodigoDoProduto")
                        .IsUnique();

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
